"""add paid_leaves table

Revision ID: 0aed95c5a315
Revises: c20c20eaf412
Create Date: 2025-10-08 09:23:05.112830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aed95c5a315'
down_revision = 'c20c20eaf412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paid_leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('leave_days_used', sa.Float(), nullable=True),
    sa.Column('remaining_leave_days', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ngay_nghi_phep_nam', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ngay_phep_con_lai', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('thang_bat_dau_tinh_phep', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.drop_column('thang_bat_dau_tinh_phep')
        batch_op.drop_column('ngay_phep_con_lai')
        batch_op.drop_column('ngay_nghi_phep_nam')

    op.drop_table('paid_leaves')
    # ### end Alembic commands ###
