"""add employee_name and employee_code to PayrollRecord

Revision ID: 1eb69b170c2d
Revises: b78548f5b47c
Create Date: 2025-10-04 16:31:12.651062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb69b170c2d'
down_revision = 'b78548f5b47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('employee_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.drop_column('employee_name')
        batch_op.drop_column('employee_code')

    # ### end Alembic commands ###
