"""init tables

Revision ID: 1f499944be4e
Revises: 
Create Date: 2025-09-30 22:28:51.558522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f499944be4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('att_code', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['att_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('att_code')

    # ### end Alembic commands ###
