"""Add new columns to payroll_records

Revision ID: 28840942fdcb
Revises: 0aed95c5a315
Create Date: 2025-10-10 16:09:25.296004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28840942fdcb'
down_revision = '0aed95c5a315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paid_leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('leave_days_used', sa.Float(), nullable=True),
    sa.Column('remaining_leave_days', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_month', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('insurance_start_month', sa.String(length=7), nullable=True))

    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standard_work_days', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ngay_nghi_phep_nam', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ngay_phep_con_lai', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('thang_bat_dau_tinh_phep', sa.String(length=50), nullable=True))

    with op.batch_alter_table('work_adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_absence_days', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('adjusted_absence_days', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ngay_vang_ban_dau', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ngay_vang_sau_gop', sa.Float(), nullable=True))
        batch_op.drop_constraint(batch_op.f('work_adjustments_payroll_record_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'payroll_records', ['payroll_record_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_adjustments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('work_adjustments_payroll_record_id_fkey'), 'payroll_records', ['payroll_record_id'], ['id'])
        batch_op.drop_column('ngay_vang_sau_gop')
        batch_op.drop_column('ngay_vang_ban_dau')
        batch_op.drop_column('adjusted_absence_days')
        batch_op.drop_column('original_absence_days')

    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.drop_column('thang_bat_dau_tinh_phep')
        batch_op.drop_column('ngay_phep_con_lai')
        batch_op.drop_column('ngay_nghi_phep_nam')
        batch_op.drop_column('standard_work_days')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('insurance_start_month')
        batch_op.drop_column('start_month')

    op.drop_table('paid_leaves')
    # ### end Alembic commands ###
