"""Add ngay_vang_ban_dau and ngay_vang_sau_gop to WorkAdjustment

Revision ID: 82fadd95bf73
Revises: c4e3421326a5
Create Date: 2025-10-07 08:03:02.301809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82fadd95bf73'
down_revision = 'c4e3421326a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ngay_vang_ban_dau', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ngay_vang_sau_gop', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_adjustments', schema=None) as batch_op:
        batch_op.drop_column('ngay_vang_sau_gop')
        batch_op.drop_column('ngay_vang_ban_dau')

    # ### end Alembic commands ###
