"""Add start_month and insurance_start_month to employees

Revision ID: a18cf66f29c5
Revises: dcb239f02e96
Create Date: 2025-10-06 15:18:25.868032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18cf66f29c5'
down_revision = 'dcb239f02e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_month', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('insurance_start_month', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('insurance_start_month')
        batch_op.drop_column('start_month')

    # ### end Alembic commands ###
