"""Add holidays table

Revision ID: acfdffff390b
Revises: 1f499944be4e
Create Date: 2025-10-04 09:38:14.907679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acfdffff390b'
down_revision = '1f499944be4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.alter_column('working_days',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('absent_days')
        batch_op.drop_column('overtime_hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overtime_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('absent_days', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('working_days',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.drop_table('holidays')
    # ### end Alembic commands ###
