"""add PayrollRecord model

Revision ID: b78548f5b47c
Revises: acfdffff390b
Create Date: 2025-10-04 14:26:13.685965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78548f5b47c'
down_revision = 'acfdffff390b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('ngay_cong', sa.Float(), nullable=True),
    sa.Column('ngay_vang', sa.Float(), nullable=True),
    sa.Column('chu_nhat', sa.Float(), nullable=True),
    sa.Column('le_tet', sa.Float(), nullable=True),
    sa.Column('tang_ca_nghi', sa.Float(), nullable=True),
    sa.Column('tang_ca_tuan', sa.Float(), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('to', sa.String(length=100), nullable=True),
    sa.Column('phong_ban', sa.String(length=100), nullable=True),
    sa.Column('loai_hd', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_records')
    # ### end Alembic commands ###
