"""add standard_work_days to payroll_record

Revision ID: c20c20eaf412
Revises: 82fadd95bf73
Create Date: 2025-10-07 09:22:12.253381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20c20eaf412'
down_revision = '82fadd95bf73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standard_work_days', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.drop_column('standard_work_days')

    # ### end Alembic commands ###
