"""Add ondelete cascade to work_adjustments

Revision ID: c4e3421326a5
Revises: a18cf66f29c5
Create Date: 2025-10-06 17:12:20.472303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e3421326a5'
down_revision = 'a18cf66f29c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_adjustments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('work_adjustments_payroll_record_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'payroll_records', ['payroll_record_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_adjustments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('work_adjustments_payroll_record_id_fkey'), 'payroll_records', ['payroll_record_id'], ['id'])

    # ### end Alembic commands ###
