"""Add le_tet_gio column to payroll_records

Revision ID: d79e83599630
Revises: 1eb69b170c2d
Create Date: 2025-10-05 12:04:44.566170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79e83599630'
down_revision = '1eb69b170c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('le_tet_gio', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.drop_column('le_tet_gio')

    # ### end Alembic commands ###
