"""Add absence days columns to work_adjustments

Revision ID: dcb239f02e96
Revises: f62c413b88af
Create Date: 2025-10-06 14:05:28.324311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb239f02e96'
down_revision = 'f62c413b88af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_absence_days', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('adjusted_absence_days', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_adjustments', schema=None) as batch_op:
        batch_op.drop_column('adjusted_absence_days')
        batch_op.drop_column('original_absence_days')

    # ### end Alembic commands ###
