"""Create work_adjustments table

Revision ID: f62c413b88af
Revises: d79e83599630
Create Date: 2025-10-05 13:56:10.735554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62c413b88af'
down_revision = 'd79e83599630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_record_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('employee_name', sa.String(length=100), nullable=True),
    sa.Column('original_work_days', sa.Float(), nullable=True),
    sa.Column('standard_work_days', sa.Float(), nullable=True),
    sa.Column('original_overtime_hours', sa.Float(), nullable=True),
    sa.Column('adjusted_work_days', sa.Float(), nullable=True),
    sa.Column('remaining_overtime_hours', sa.Float(), nullable=True),
    sa.Column('used_overtime_hours', sa.Float(), nullable=True),
    sa.Column('adjustment_type', sa.String(length=50), nullable=True),
    sa.Column('adjustment_reason', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_record_id'], ['payroll_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_adjustments')
    # ### end Alembic commands ###
